local mod = get_mod("weapon_customization")

mod.package_manager = Managers.package
mod.packages = {}

mod.load_packages = function(self)
    self:load_package("content/weapons/player/attachments/flashlights/flashlight_01/flashlight_01")
	self:load_package("content/weapons/player/attachments/flashlights/flashlight_02/flashlight_02")
	self:load_package("content/weapons/player/attachments/flashlights/flashlight_03/flashlight_03")
	self:load_package("content/weapons/player/attachments/flashlights/flashlight_04/flashlight_04")
	self:load_package("content/weapons/player/attachments/flashlights/flashlight_05/flashlight_05")

    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/barrel_01/barrel_01")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/barrel_02/barrel_02")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/barrel_03/barrel_03")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/receiver_01/receiver_01")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/receiver_02/receiver_02")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/receiver_03/receiver_03")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/magazine_01/magazine_01")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/magazine_02/magazine_02")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/magazine_03/magazine_03")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/grip_01/grip_01")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/grip_02/grip_02")
    self:load_package("content/weapons/player/ranged/stubgun_heavy_ogryn/attachments/grip_03/grip_03")

    self:load_package("content/weapons/player/melee/combat_sword/attachments/blade_01/blade_01")

    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/barrel_01/barrel_01")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/barrel_02/barrel_02")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/barrel_03/barrel_03")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/barrel_04/barrel_04")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/barrel_05/barrel_05")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/barrel_06/barrel_06")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/receiver_01/receiver_01")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/receiver_02/receiver_02")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/receiver_03/receiver_03")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/receiver_04/receiver_04")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/receiver_05/receiver_05")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/receiver_06/receiver_06")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/magazine_01/magazine_01")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/magazine_02/magazine_02")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/magazine_03/magazine_03")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/magazine_04/magazine_04")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/magazine_05/magazine_05")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/magazine_06/magazine_06")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/bayonet_01/bayonet_01")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/bayonet_02/bayonet_02")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/bayonet_03/bayonet_03")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/handle_01/handle_01")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/handle_02/handle_02")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/handle_03/handle_03")
    self:load_package("content/weapons/player/ranged/rippergun_rifle/attachments/handle_04/handle_04")

    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/sight_01/sight_01")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/sight_02/sight_02")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/sight_03/sight_03")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/sight_04/sight_04")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/grip_01/grip_01")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/grip_02/grip_02")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/grip_03/grip_03")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/grip_04/grip_04")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/grip_05/grip_05")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/body_01/body_01")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/body_02/body_02")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/body_03/body_03")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/body_04/body_04")
    self:load_package("content/weapons/player/ranged/shotgun_grenade/attachments/body_05/body_05")

    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/barrel_01/barrel_01")
    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/barrel_02/barrel_02")
    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/barrel_03/barrel_03")
    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/barrel_04/barrel_04")
    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/body_01/body_01")
    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/body_02/body_02")
    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/body_03/body_03")
    self:load_package("content/weapons/player/ranged/gauntlet_basic/attachments/body_04/body_04")

    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/grip_01/grip_01")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/grip_02/grip_02")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/grip_03/grip_03")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/grip_04/grip_04")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/grip_05/grip_05")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/pommel_01/pommel_01")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/pommel_02/pommel_02")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/pommel_03/pommel_03")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/pommel_04/pommel_04")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/pommel_05/pommel_05")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/head_01/head_01")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/head_02/head_02")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/head_03/head_03")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/head_04/head_04")
    self:load_package("content/weapons/player/melee/shovel_ogryn/attachments/head_05/head_05")
    
    self:load_package("content/weapons/player/melee/combat_blade/attachments/blade_01/blade_01")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/blade_02/blade_02")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/blade_03/blade_03")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/blade_04/blade_04")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/blade_05/blade_05")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/blade_06/blade_06")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/grip_01/grip_01")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/grip_02/grip_02")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/grip_03/grip_03")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/grip_04/grip_04")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/grip_05/grip_05")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/grip_06/grip_06")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/handle_01/handle_01")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/handle_02/handle_02")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/handle_03/handle_03")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/handle_04/handle_04")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/handle_05/handle_05")
    self:load_package("content/weapons/player/melee/combat_blade/attachments/handle_06/handle_06")

    self:load_package("content/weapons/player/melee/power_maul/attachments/shaft_01/shaft_01")
    self:load_package("content/weapons/player/melee/power_maul/attachments/shaft_02/shaft_02")
    self:load_package("content/weapons/player/melee/power_maul/attachments/shaft_03/shaft_03")
    self:load_package("content/weapons/player/melee/power_maul/attachments/shaft_04/shaft_04")
    self:load_package("content/weapons/player/melee/power_maul/attachments/shaft_05/shaft_05")
    self:load_package("content/weapons/player/melee/power_maul/attachments/head_01/head_01")
    self:load_package("content/weapons/player/melee/power_maul/attachments/head_02/head_02")
    self:load_package("content/weapons/player/melee/power_maul/attachments/head_03/head_03")
    self:load_package("content/weapons/player/melee/power_maul/attachments/head_04/head_04")
    self:load_package("content/weapons/player/melee/power_maul/attachments/head_05/head_05")
    self:load_package("content/weapons/player/melee/power_maul/attachments/pommel_01/pommel_01")
    self:load_package("content/weapons/player/melee/power_maul/attachments/pommel_02/pommel_02")
    self:load_package("content/weapons/player/melee/power_maul/attachments/pommel_03/pommel_03")
    self:load_package("content/weapons/player/melee/power_maul/attachments/pommel_04/pommel_04")
    self:load_package("content/weapons/player/melee/power_maul/attachments/pommel_05/pommel_05")

    self:load_package("content/weapons/player/melee/club_pipe_ogryn/attachments/mk1/club_pipe_01")
    self:load_package("content/weapons/player/melee/club_pipe_ogryn/attachments/mk2/club_pipe_02")
    self:load_package("content/weapons/player/melee/club_pipe_ogryn/attachments/mk3/club_pipe_03")
    self:load_package("content/weapons/player/melee/club_pipe_ogryn/attachments/mk4/club_pipe_04")
    self:load_package("content/weapons/player/melee/club_pipe_ogryn/attachments/mk5/club_pipe_05")

end

mod.load_package = function(self, package_name)
	if not self.package_manager:is_loading(package_name) and not self.package_manager:has_loaded(package_name) then
        self.packages[#self.packages+1] = package_name
		return self.package_manager:load(package_name, "weapon_customization", nil, true)
	end
end

mod:load_packages()