local mod = get_mod("pure_cinema")

return {
	name = mod:localize("mod_title"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{["setting_id"] = "group_weapon_discharge",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "weapon_discharge",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "weapon_discharge_tooltip",
					},
					{["setting_id"] = "weapon_discharge_collision_check",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "weapon_discharge_collision_check_tooltip",
					},
					{["setting_id"] = "discharge_on_death_chance",
						["type"] = "numeric",
						["default_value"] = 50,
						["range"] = {0, 100},
						["decimals_number"] = 0,
						["tooltip"] = "discharge_on_death_chance_tooltip",
					},
				},
			},
			{["setting_id"] = "group_helmet",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "helmet_drop",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "helmet_drop_tooltip",
					},
					{["setting_id"] = "helmet_drop_collision_check",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "helmet_drop_collision_check_tooltip",
					},
				},
			},
			{["setting_id"] = "group_struggle",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "struggle",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "struggle_tooltip",
					},
					{["setting_id"] = "struggle_on_death_chance",
						["type"] = "numeric",
						["default_value"] = 25,
						["range"] = {0, 100},
						["decimals_number"] = 0,
						["tooltip"] = "struggle_on_death_chance_tooltip",
					},
				},
			},
			{["setting_id"] = "group_heavier_ragdolls",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "heavier_ragdolls",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "heavier_ragdolls_tooltip",
					},
				},
			},
			{["setting_id"] = "group_fall_sounds",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "fall_sounds",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "fall_sounds_tooltip",
					},
					{["setting_id"] = "fall_sounds_collision_check",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "fall_sounds_collision_check_tooltip",
					},
				},
			},
			{["setting_id"] = "group_debug",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "clear_chat",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "clear_chat",
					},
					{["setting_id"] = "debug_mode",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip"] = "debug_mode_tooltip",
					},
					{["setting_id"] = "load_mission_intro_view",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "load_mission_intro_view",
					},
					{["setting_id"] = "load_end_view",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "load_end_view",
					},
					{["setting_id"] = "load_lobby_view",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "load_lobby_view",
					},
				},
			},
		},
	},
}
