local mod = get_mod("modding_tools")

return {
	name = "modding_tools",
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{["setting_id"] = "Console",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "console_drawing_time",
						["type"] = "checkbox",
						["default_value"] = true,
					},
					{["setting_id"] = "hook_echo",
						["type"] = "checkbox",
						["default_value"] = false,
					},
					{["setting_id"] = "hook_error",
						["type"] = "checkbox",
						["default_value"] = false,
					},
					{["setting_id"] = "hook_warning",
						["type"] = "checkbox",
						["default_value"] = false,
					},
					{["setting_id"] = "hook_info",
						["type"] = "checkbox",
						["default_value"] = false,
					},
					{["setting_id"] = "hook_notify",
						["type"] = "checkbox",
						["default_value"] = false,
					},
				},
			},
			{["setting_id"] = "watcher",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "watcher_drawing_time",
						["type"] = "checkbox",
						["default_value"] = true,
					},
				},
			},
			{["setting_id"] = "inspector",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "inspector_drawing_time",
						["type"] = "checkbox",
						["default_value"] = true,
					},
					{["setting_id"] = "hook_dtf",
						["type"] = "checkbox",
						["default_value"] = false,
					},
				},
			},
			{["setting_id"] = "keybindings",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "toggle_ui",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "toggle_ui",
					},
				},
			},
			-- {["setting_id"] = "redirect_inspect",
  			-- 	["type"] = "group",
			-- 	["sub_widgets"] = {
			-- 		{["setting_id"] = "hook_dtf",
			-- 			["type"] = "checkbox",
			-- 			["default_value"] = false,
			-- 		},
			-- 	},
			-- },
			-- {["setting_id"] = "redirect_console",
  			-- 	["type"] = "group",
			-- 	["sub_widgets"] = {
			-- 		{["setting_id"] = "hook_echo",
			-- 			["type"] = "checkbox",
			-- 			["default_value"] = false,
			-- 		},
			-- 		{["setting_id"] = "hook_error",
			-- 			["type"] = "checkbox",
			-- 			["default_value"] = false,
			-- 		},
			-- 		{["setting_id"] = "hook_warning",
			-- 			["type"] = "checkbox",
			-- 			["default_value"] = false,
			-- 		},
			-- 		{["setting_id"] = "hook_info",
			-- 			["type"] = "checkbox",
			-- 			["default_value"] = false,
			-- 		},
			-- 		{["setting_id"] = "hook_notify",
			-- 			["type"] = "checkbox",
			-- 			["default_value"] = false,
			-- 		},
			-- 	},
			-- },
			-- {["setting_id"] = "toggle_ui",
			-- 	["type"] = "keybind",
			-- 	["default_value"] = {},
			-- 	["keybind_trigger"] = "pressed",
			-- 	["keybind_type"] = "function_call",
			-- 	["function_name"] = "toggle_ui",
			-- },
		},
	},
}
