local mod = get_mod("extended_weapon_customization")

return {
	name = mod:localize("mod_title"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{["setting_id"] = "group_randomize",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "mod_option_randomize_players",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_option_randomize_players_tooltip",
					},
					{["setting_id"] = "mod_option_randomize_store",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_option_randomize_store_tooltip",
					},
					{["setting_id"] = "mod_option_randomize_reward",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_option_randomize_reward_tooltip",
					},
				},
			},
			{["setting_id"] = "group_misc",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "mod_option_sway",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_option_sway_tooltip",
					},
					{["setting_id"] = "mod_option_crouch",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_option_crouch_tooltip",
					},
					{["setting_id"] = "mod_option_crouch_melee",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip"] = "mod_option_crouch_melee_tooltip",
					},
					{["setting_id"] = "mod_weapon_dof_strength",
						["type"] = "numeric",
						["default_value"] = .5,
						["range"] = {0, 1},
						["decimals_number"] = 1,
						["tooltip"] = "mod_weapon_dof_strength_tooltip",
					},
				},
			},
			{["setting_id"] = "group_flashlight",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "mod_option_flashlight_shadows",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_option_flashlight_shadows_tooltip",
					},
					{["setting_id"] = "mod_toggle_flashlight_interact_aim",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_toggle_flashlight_interact_aim_tooltip",
					},
					{["setting_id"] = "mod_toggle_flashlight_interact_double",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_toggle_flashlight_interact_double_tooltip",
					},
					{["setting_id"] = "mod_flashlight_input_reminder",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_flashlight_input_reminder_tooltip",
					},
				},
			},
			{["setting_id"] = "group_debug",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "clear_chat",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "clear_chat",
					},
					{["setting_id"] = "debug_mode",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip"] = "debug_mode_tooltip",
					},
				},
			},
			{["setting_id"] = "group_sight_debug",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "rotate_x",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "rotate_x",
					},
					{["setting_id"] = "rotate_x_2",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "rotate_x_2",
					},
					{["setting_id"] = "rotate_y",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "rotate_y",
					},
					{["setting_id"] = "rotate_y_2",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "rotate_y_2",
					},
					{["setting_id"] = "rotate_z",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "rotate_z",
					},
					{["setting_id"] = "rotate_z_2",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "rotate_z_2",
					},
					{["setting_id"] = "move_x",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "move_x",
					},
					{["setting_id"] = "move_x_2",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "move_x_2",
					},
					{["setting_id"] = "move_y",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "move_y",
					},
					{["setting_id"] = "move_y_2",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "move_y_2",
					},
					{["setting_id"] = "move_z",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "move_z",
					},
					{["setting_id"] = "move_z_2",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "move_z_2",
					},
				},
			},
		},
	},
}
