local mod = get_mod("extended_weapon_customization")

return {
	name = mod:localize("mod_title"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{["setting_id"] = "group_misc",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "mod_option_sway",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip"] = "mod_option_sway_tooltip",
					},
				},
			},
			{["setting_id"] = "group_flashlight",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "mod_option_flashlight_shadows",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip"] = "mod_option_flashlight_shadows_tooltip",
					},
					{["setting_id"] = "mod_toggle_flashlight_interact_aim",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_toggle_flashlight_interact_aim_tooltip",
					},
					{["setting_id"] = "mod_toggle_flashlight_interact_double",
						["type"] = "checkbox",
						["default_value"] = true,
						["tooltip"] = "mod_toggle_flashlight_interact_double_tooltip",
					},
				},
			},
			{["setting_id"] = "group_debug",
  				["type"] = "group",
				["sub_widgets"] = {
					{["setting_id"] = "clear_chat",
						["type"] = "keybind",
						["default_value"] = {},
						["keybind_trigger"] = "pressed",
						["keybind_type"] = "function_call",
						["function_name"] = "clear_chat",
					},
					{["setting_id"] = "debug_mode",
						["type"] = "checkbox",
						["default_value"] = false,
						["tooltip"] = "debug_mode_tooltip",
					},
				},
			},
		},
	},
}
